### ISSUE TITLE
seared glass recipe loop

### ISSUE THREAD

**Issue by Codystar44** [dawsontech30000/formymodpack#1]
![2022-11-28_10 26 46](https://user-images.githubusercontent.com/30987799/204374231-6828790c-bfc0-41ce-992e-31a440d78ab7.png)
![2022-11-28_10 26 44](https://user-images.githubusercontent.com/30987799/204374261-05f1c990-c938-49c7-80c4-2c3773f20e09.png)

**Comment by dawsontech30000** [comment]
thanks for reporting the bug

**Comment by dawsontech30000** [comment]
this will be fixed next update

**Comment by dawsontech30000** [comment]
fixed
