### ISSUE TITLE
Sun is flashbang bug

### ISSUE THREAD

**Issue by Katzo03** [dawsontech30000/formymodpack#4]
https://user-images.githubusercontent.com/121289962/218275402-ab7399f1-91b8-476a-953b-401e2ddc6074.mp4

**Comment by Dawsondude2023** [comment]
get to this tomrrow

**Comment by Dawsondude2023** [comment]
fixed to fixed till next update
![image](https://user-images.githubusercontent.com/115547663/218761078-c157bb36-113c-4955-b3bf-8eae8d653096.png)
![image](https://user-images.githubusercontent.com/115547663/218761148-a97480b4-dbc8-4f0a-b740-c3767223fa1b.png)

**Comment by Dawsondude2023** [comment]
let me know if still happen with these false
